server {
    server_name example.com
    listen 8080
    listen 3000
    root /var/www/example.com
    index index.html

    location / {
        methods GET POST
        root /var/www/example.com/public
        index index.html
	}
