server {
    server_name tdefault
    listen 8080
    root /var/www/test.com
    index index.html
    max_body_size 300000

    location / {
        methods GET POST
        root /var/www/example.com/public
        index index.html
    }

    error_page  /errors/404.html
}