server {
    server_name default_file
    listen 8080
    root ./public
    index index.html
    max_body_size 300000

    location / {
        methods GET POST
        root /
        index index.html
		default_location true
    }
    error_path  ./public/errors/
}
