server {
    server_name localhost
    listen 8080
    listen 3000
    root ./public
    index index.html
    max_body_size 4194304

    location / {
        methods GET POST
        root /
        index index.html
		default_location true
    }

    location /uploads {
        methods GET POST
        root user_uploads
        accept_uploads yes
    }

    location /download {
        methods GET
        root user_uploads
		auto_index true
    }

    location /delete {
        methods DELETE
        root /delete_test
    }

    location /cgi {
        methods GET POST
        root /cgi-bin
        fastcgiPass python3
        fastcgiIndex .py
    }

    error_path ./public/errors/
}

server {
    server_name 127.0.0.1
    listen 4247
	listen 8080
    root /var/www/test.com
    index index.html
    max_body_size 300000

    location /cgi {
		default_location yes
        methods GET POST
        fastcgiPass /cgi-bin/calculator.py
        fastcgiIndex .py
    }

    error_path  ./public/errors/
}
