server {
    server_name test.com
    listen 8080
    listen 3000
    root ./public
    index index.html
    max_body_size 10000000000

    location / {
        methods GET POST
        root /
        index index.html
        return_url ./public/index.html
		default_location true
    }

    location /uploads {
        methods GET POST
        root user_uploads
        return_url blabla
        accept_uploads yes
    }

    location /download {
        methods GET
        root user_uploads
        return_url blabla
    }

    location /delete {
        methods DELETE
        root /delete_test
    }

    location /cgi {
        methods GET
        root /cgi-bin
        fastcgiPass /cgi-bin/script.py
        fastcgiIndex .py
    }

    error_page ./public/errors/40x.html
}

server {
    server_name example.com
    listen 4247
    root /var/www/test.com
    index index.html
    max_body_size 300000

    location /cgi {
		default_location yes
        methods GET
        fastcgiPass /cgi-bin/script.py
        fastcgiIndex .py
    }

    error_page  ./public/errors/404.html
}
