server {
    server_name test.com
    listen 8080
    listen 3000
    root ./public
    index index.html
    max_body_size 300000

    location / {
        methods GET POST
        root ./public
        index /index.html
        return_url ./public/index.html
    }

    location /uploads {
        methods GET POST
        root ./public
        return_url blabla
        accept_uploads yes
    }

    location /delete {
        methods DELETE
        root ./public
    }
    location /cgi-bin {
        methods GET
        root ./public/cgi-bin
        fastcgiPass /cgi-bin/script.py
        fastcgiIndex .py
    }

    error_page ./public/errors/40x.html
}

server {
    server_name example.com
    listen 4247
    root /var/www/test.com
    index index.html
    max_body_size 300000

    location /cgi {
        methods GET
        fastcgiPass /cgi-bin/script.py
        fastcgiIndex .py
    }

    error_page  ./public/errors/404.html
}
