server {
    listen 8080
    index index.html

    location / {
        methods GET POST
        index index.html
    }

    location /upload {
        methods POST
        root /var/www/example.com/uploads
    }

    error_page 404 /404.html
}
